# Generated by Django 4.1.7 on 2023-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('img', models.ImageField(default='product.jpg', upload_to='product')),
                ('price', models.FloatField()),
                ('max_quantity', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('brands', models.CharField(default=50, max_length=50)),
                ('description', models.TextField()),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('date_uploaded', models.DateField(auto_now=True)),
            ],
        ),
    ]
