# Generated by Django 4.1.7 on 2023-04-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
