# Generated by Django 4.1.7 on 2023-04-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
