# Generated by Django 4.1.7 on 2023-04-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin',
        ),
    ]
