# Generated by Django 4.1.7 on 2023-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_payment_options_alter_shopcart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shopcart',
            table='shopcart',
        ),
    ]
