# Generated by Django 4.1.7 on 2023-04-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
