# Generated by Django 4.1.7 on 2023-04-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_profile_address_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
